# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 71d4ac097460e34c06d89dfcaf4d70da295a16651cb3859c9180621a80ae3cb0ef6968e2da662054356524a6a2fde2811d5735c23a549403ab999556c68a27f7

test:
  secret_key_base: 260ba00dacd0b7dca6fe80b16a8de22b38ae96321c663f190f855e1b610f739d283ada009b1c68ef1a16945bfad33fafb8af623535d300cf629a21b7ac4d1c6f

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
